server:
  port: 8081
# 服务名称
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 114.55.75.141
    port: 6379
    password: 123321
    # 连接池配置
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  # json序列化
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  # 别名扫描包
  main:
    banner-mode: off
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  global-config:
    banner: false
logging:
  level:
    com.hmdp: debug